spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
  datasource:
    # https://zetcode.com/springboot/postgresql/
    url: jdbc:postgresql://localhost:5432/cable
    username: cable-data-base
    password: KKZ0comp
    initialization-mode: always
    platform: postgres
  # h2.console.enabled: true
